### ISSUE TITLE
Wallet cannot connect

### ISSUE THREAD

**Issue by jetta20162** [SynchrotronCoinDev/SynchrotronCoin#2]
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs
connection timeout
trying connection 45.32.238.57:44445 lastseen=132.8hrs

**Comment by SynchrotronCoinDev** [comment]
do you add the nodes to your synchrotroncoin.conf?

**Comment by jetta20162** [comment]
I tried to add them in the debug console but the addnode command is not supported. The conf file i don't have inside the folder

**Comment by jetta20162** [comment]
i created the config file and it is working now
